apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mstress-memory
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mstress
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70