apiVersion: v1
kind: Pod
metadata:
  labels:
    run: utils
  name: utils
spec:
  containers:
  - image: alpine:3.14
    name: utils
    command:
    - /bin/sh
    - -c
    - sleep 4800
    resources: {}
  dnsPolicy: ClusterFirst
  dnsConfig:
    nameservers:
    - 192.168.64.1
    options:
    - name: ndots
      value: "2"
    - name: edns0
  restartPolicy: Always
status: {}
